### PR TITLE
updates to mathml, svg, and equation topics

### PR DESCRIPTION
**Pull request by nancylph**
updated topics for review by kris and robert

### CODE REVIEW

**Comment by robander** [comment]
It looks like these topics took the DITA 1.3 versions as their starting point, rather than starting with the latest versions from the DITA 2.0 branch. They lose all of the content updates we've made for 2.0 -- the sections use the old 1.3 names, attribute sections are out of date, and short descriptions go back to the old style.

@nancylph we cannot merge these as is, because they would remove dozens of updates and fixes from the last few years. I'm not sure how you want to handle the changes at this point - I suspect you spent quite a lot of time and attention on these edits, so I'm not sure if you want (or have the time) to start over with new versions based on the latest 2.0 topics. Given all the organizational changes in the files, I don't see an easy way to pick out edits that would still apply to the latest versions of the topics.

**Comment by nancylph** [comment]
Hi Robert,

I'm not sure how that could have happened.  I created my branch, and
checked stuff out, directly under Kris's supervision.  Then I updated the
topics according to the editorial guidelines document she put out, checked
my changes against some of  the langef topics in our most recent reviews to
make sure that my results were in line with them, and afterwards staged,
committed, and pushed them back to my remote tree also under her explicit
supervision.   Can you email me a copy of a file you looked at, just to
make sure we're looking at the same files?

Thanks,
Nancy


_____________
Nancy Harrison
Infobridge Solutions
***@***.***

**Comment by keberlein** [comment]
Nancy, I think what happened is when you first created your branch — and I was not around for that — you created it from main or the hot fix branch, instead of the DITA-2.0 branch.

Kris

**Comment by keberlein** [comment]
I take this back — I remember now that I did help you get set up with SourceTree and create a branch. Perhaps you later made some changes? When I helped you this week, you were on a detached head and in the midst of rebasing … 

Kris

**Comment by robander** [comment]
@nancylph to check the files - the easiest way is to look at the top of this pull request and click on the "Files changed" tab, right below the title / right above your original description. That will show a side-by-side diff of all changes that would go in if we merge this. That view is what I was basing my comments on, and is the easiest way to verify what changes your pull request would make.

**Comment by robander** [comment]
Closing as obsolete - the changes were merged from another branch: https://github.com/oasis-tcs/dita-techcomm/pull/223

**Comment by nancylph** [comment]
So I'm not sure what happened; I had made changes to some of the examples
just before I checked them into the 2.0 branch; did those get included?

Nancy

_____________
Nancy Harrison
Infobridge Solutions
***@***.***

**Comment by keberlein** [comment]
Hi, Nancy.I merged what you had on your branch into the TC repo. And I add some edits. We’ll open a review of the content tomorrow. If there are other changes that you think we’ll need to make to the examples, you can suggest them in the review.KrisSent from my iPadOn Apr 3, 2023, at 9:45 PM, nancylph ***@***.***> wrote:﻿
So I'm not sure what happened; I had made changes to some of the examples
just before I checked them into the 2.0 branch; did those get included?

Nancy

_____________
Nancy Harrison
Infobridge Solutions
***@***.***

**Pull request closed without merging**
